// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get(arg1) {
  return window['go']['jsonstore']['Service']['Get'](arg1);
}

export function List() {
  return window['go']['jsonstore']['Service']['List']();
}

export function Remove(arg1) {
  return window['go']['jsonstore']['Service']['Remove'](arg1);
}

export function RemoveMany(arg1) {
  return window['go']['jsonstore']['Service']['RemoveMany'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['jsonstore']['Service']['Rename'](arg1, arg2);
}

export function Save(arg1, arg2, arg3) {
  return window['go']['jsonstore']['Service']['Save'](arg1, arg2, arg3);
}

export function SetPin(arg1, arg2) {
  return window['go']['jsonstore']['Service']['SetPin'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['jsonstore']['Service']['Startup'](arg1);
}
