// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {jsonstore} from '../models';
import {context} from '../models';

export function Get(arg1:string):Promise<jsonstore.Payload>;

export function List():Promise<Array<jsonstore.Doc>>;

export function Remove(arg1:string):Promise<jsonstore.Result>;

export function RemoveMany(arg1:Array<string>):Promise<jsonstore.Result>;

export function Rename(arg1:string,arg2:string):Promise<jsonstore.Result>;

export function Save(arg1:string,arg2:string,arg3:string):Promise<jsonstore.SaveResult>;

export function SetPin(arg1:string,arg2:boolean):Promise<jsonstore.Result>;

export function Startup(arg1:context.Context):Promise<void>;
