// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {jsontool} from '../models';

export function Diff(arg1:string,arg2:string):Promise<jsontool.DiffResult>;
