// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugintool} from '../models';
import {context} from '../models';

export function Import():Promise<plugintool.ImportResult>;

export function List():Promise<Array<plugintool.Plugin>>;

export function Middleware():Promise<any>;

export function Remove(arg1:string):Promise<plugintool.RemoveResult>;

export function Startup(arg1:context.Context):Promise<void>;
