// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Import() {
  return window['go']['plugintool']['Service']['Import']();
}

export function List() {
  return window['go']['plugintool']['Service']['List']();
}

export function Middleware() {
  return window['go']['plugintool']['Service']['Middleware']();
}

export function Remove(arg1) {
  return window['go']['plugintool']['Service']['Remove'](arg1);
}

export function Startup(arg1) {
  return window['go']['plugintool']['Service']['Startup'](arg1);
}
