// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Meta() {
  return window['go']['app']['App']['Meta']();
}

export function OnSecondInstance(arg1) {
  return window['go']['app']['App']['OnSecondInstance'](arg1);
}

export function RequestQuit() {
  return window['go']['app']['App']['RequestQuit']();
}

export function ShouldHideOnClose() {
  return window['go']['app']['App']['ShouldHideOnClose']();
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}
