// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {options} from '../models';
import {context} from '../models';

export function Meta():Promise<app.AppMeta>;

export function OnSecondInstance(arg1:options.SecondInstanceData):Promise<void>;

export function RequestQuit():Promise<void>;

export function ShouldHideOnClose():Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;
