// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenTextFile() {
  return window['go']['platform']['Platform']['OpenTextFile']();
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['platform']['Platform']['SaveTextFile'](arg1, arg2);
}

export function SetClipboard(arg1) {
  return window['go']['platform']['Platform']['SetClipboard'](arg1);
}

export function Startup(arg1) {
  return window['go']['platform']['Platform']['Startup'](arg1);
}
