// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {platform} from '../models';
import {context} from '../models';

export function OpenTextFile():Promise<platform.FileResult>;

export function SaveTextFile(arg1:string,arg2:string):Promise<string>;

export function SetClipboard(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
